### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#126]
Check ISO 8601 formatting of the ingest date field from metadata scraper

**Comment by mcquinne** [comment]
Turns out this is actually part of the LightEngine: it attaches a `dateSent` field to every rabbit message it sends using a format with no time zone.

I don't want to just change since I don't know if other parts of common ingest are utilizing it or not, so I'll chat with the folks in Asheville and see what they say.

WRT the `ingestTime`field that we're adding in metadata-scraper, it is indeed in full ISO format in UTC: https://github.com/cedardevs/ingest-engines/blob/468d91f70c7d76d3ec6633112a78202bbe69f7cb/metadata-scraper/src/main/groovy/ngdc/ingest/MetadataScraper.groovy#L48

**Comment by mcquinne** [comment]
We could potentially strip this out of what metadata-publisher posts? Not sure if that's worth it or not.

**Comment by StrayCat1** [comment]
Created an issue on the ingest-engine repo.  That date should include the timestamp, but it is low priority. Closing this issue on the psi board.
