### ISSUE TITLE
s3 archiver

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#127]
Broke, why? Fix.

**Comment by StrayCat1** [comment]
s3-archiver suddenly decided to start working...
https://sciapps.colorado.edu/ingest-manager/granule/show/3558

I think the issue was actually with ingest-manager not s3-archiver. When I was trying to fix this locally, I realized I had an old ingest-manager image that wasnt displaying s3-archiver as an option, even though it showed up in a pre-existing stream config I had made months ago. I think what happened here is someone built and pushed an ingest-manager image that did not have the s3-archiver branch merged into it. When I pulled the latest image and redeployed, it worked. The only flaw in that theory is that the ingest-manager image hasnt been updated in a month.... so what the frick? no idea. Probably just god making sure our demo wasnt too good. 

It works... shhh... dont ask the hard questions.
