### ISSUE TITLE
Implement dscovr ingest w/ modern engines

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/psi#17]
First pass point dscovr datastream at metadata-recorder instead of dscovr-engine.
Use CCI lightengine approach?

Steps from existing engine:
- [x] validate path
- [x] metadata-recorder
- [x] path-transformer?
- [x] archive
- [x] Merge to master

Also:
- [x] Identify any other steps from existing processor which need to be implemented in modern engines

The goal:
1. The legacy dscovr engine is no longer needed
2. Publish enough metadata about dscovr granules into PSI to enable OS discovery

**Comment by Ghebrechristos** [comment]
Dscovr file name will be validated via path-validator engine. part of this work, the path-validator engine is updated to use light engine

**Comment by Ghebrechristos** [comment]
new metadata scraper engine got created

**Comment by Ghebrechristos** [comment]
Path-transformer will be used to extract relative path prefix, data, month from the incoming file name

**Comment by Ghebrechristos** [comment]
For archiving  files we going to use the new hpss-archiver engine. This engine have a jar dependency from a different project ( ingest-manifest ) after talking with Asheville  folks we decide to add ingest-manifest (legacy engine ) to the engines project  instead of independently build it and drop it to a location where the engine are pointing at

**Comment by ChrisEsterlein** [comment]
New engines reviewed, generic stream implemented, deployed to CU

**Comment by ChrisEsterlein** [comment]
New engines reviewed, generic stream implemented, deployed to CU
