### ISSUE TITLE
dscovr granule embargo feature

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/psi#71]
Goal: Respect the embargo flag in the filename

Background:
- There is a flag in the filename that indicates whether a file should be embargoed
- However, that flag does *not* fit into the ISOLite metadata

Strawman:
- SME scripts are able to return both ISOLite and also inventory info

**Comment by mcquinne** [comment]
Example of what a SME script could return:

```json
{
   "discoveryInfo":  ISOLite|OS-JSON,
    "publish": true|false
}
```

**Comment by mcquinne** [comment]
Considerations:
- There may be different reasons for something to be non-public... maybe include a "reason" field or something? (e.g. litigation holds)
- Some data are only private for a given time period, so maybe we need to allow a date in addition to just true/false?
- Another flag/date is a "retention schedule" ... could be a different story

**Comment by dneufeldcu** [comment]
updated JSON above to reflect comment

**Comment by mcquinne** [comment]
Updates based on most recent conversations:

- We'll update the output of SME functions to return a map of publishing info rather than a single flag:
    ```
    {
      "publishing": {
        "private": true,
        "publishDate": "2020-01-01"
      },
      ...
    }
    ```
- We'll create a delayed publishing processor (or transformer) with the Kafka Streams API to implement automatic, future updates to publishing state. It'll use an internal KTable to map timestamps to granule keys and use the `punctuate` functionality to trigger the state changes.
- **We must consider possible permutations of granule updates + publish triggers**
    - Permutation #1:
        - Granule says publish in 2020
        - In 2019, granule updated to publish in 2021
        - In 2020, we must recognize that we should still *not* publish the granule
    - Permutation #2:
        - Granule says publish in 2019
        - In 2019, granule is published
        - In 2020, granule updated to say publish in 2021
        - Granule must be *deleted* in downstream apps as it was already published
    - Others?
