### ISSUE TITLE
CI Engine to push files to S3

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/psi#74]
- [x] Put file in s3 bucket, literally
- [x] Actually, publish s3 location to PSI

**Comment by cEsterlein** [comment]
In actuality, this is literally done, for real.... as a first pass. 

https://github.com/cedardevs/ingest-engines/tree/s3Archiver/s3-archiver

**Comment by Ghebrechristos** [comment]
The s3 engine is in s3-archiver branch and part of this review i didn't see any pull request, does it need to be merge to master ?

**Comment by Ghebrechristos** [comment]
-[] Unit test 
-[] pull request

**Comment by mcquinne** [comment]
I added a test that actually exercises the engine code and have come up with several things that we could address in the process:

1. The region `s3-us-west-1` is currently hard-coded into the URLs that get published to the inventory manager which doesn't feel like a good idea.
1. We should maybe use more generic keys than `enterpriseDownloadLink` and `enterpriseDownloadLinkProtocol` since those are things that our SME just made up.
1. We should at least think about using something besides just the name of the file for the key to prevent collisions.
1. The massive handler closure could stand to be refactored.

**Comment by cEsterlein** [comment]
1) Definitely want to make that base url/region configurable. We should fix this before pushing to master.
2) Yeah, those are just what William's script referenced, figured we would know what that actually is when we start formalizing our message structure and defining our SME script requirements. 
3) I did that for dscovr because William had put so much thought into the file names, they shouldn't ever collide, and it made a good demonstration. But yeah, I was thinking the real key should probably be some kind of hash. They have a [best practices guide for keying objects ](https://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html) that actually advises against sequential keys due to the way s3 partitions objects. Maybe we just use the tracking_id... seems simple. Also, we should also think about what happens when you try to put 
4) Yeah, it needs refactored bad. While we are at it- like 50% of the code in s3-archiver is the same as metadata-scraper.  What is the best way to reuse code here? 

But yeah, all good questions/comments. We should probably fix at least 1 and 4 before we merge this branch with master. I can take that on if you want.
